### ISSUE TITLE
Improve `directories` in configuration

### ISSUE THREAD

**Issue by ruudk** [twigstan/twigstan#13]
It's currently not clear that TwigStan scans for both Twig templates and PHP code in `directories`.

Maybe this should be split up:

```neon
parameters:
  twigstan:
    directories:
      twig:
        - templates
      php: 
        - src/Controller
```

**Comment by raffaelecarelle** [comment]
Maybe is more clear use **php_controllers** or only **controllers** instead of php. In theory twigstan does an analysis for php controller renderpoints and not all php files or am I wrong?

**Comment by ruudk** [comment]
Most of the time yes, but not always. There can be other places that use Twig to render things. For example, for email or notifications. With the new [TemplateContextCollector](https://github.com/twigstan/twigstan/blob/main/src/PHPStan/Collector/TemplateContextCollector.php) it can be found anywhere.

**Comment by raffaelecarelle** [comment]
I see...thank you for explanation :)

**Comment by ruudk** [comment]
If you want to give this a try, please go ahead 😊

**Comment by raffaelecarelle** [comment]
I would be happy :)
