### ISSUE TITLE
Improve test suite

### ISSUE THREAD

**Issue by ruudk** [twigstan/twigstan#14]
Currently most tests are failing.

Since TwigStan does a few steps that all together should work, I think it would be best to create a few good functional tests that use TwigStan to analyze Twig/PHP fixtures, and then have assertions on expected errors.

**Comment by raffaelecarelle** [comment]
Hi @ruudk, if I can help, just tell me what I should d :)

thank you!

**Comment by ruudk** [comment]
@raffaelecarelle I sent you a message on [Symfony Slack](https://symfony-devs.slack.com/join/shared_invite/zt-2lzu838f9-4dVx4LaFmH8Hd9yiC67BVw#/shared-invite/email)
