### ISSUE TITLE
Cannot get offset "0" on "array<App\Entity\TranslationLog>".

### ISSUE THREAD

**Issue by VincentLanglet** [twigstan/twigstan#155]
Why do I get this error ? 

I feel like twigstan is stricter than phpstan itself
https://phpstan.org/r/082b6a51-1446-4f11-9ee3-27ac45a63441

And I get this error with the code
```
{% if translationLogs[0] is defined %}
     <small>{{ (translationLogs[0].createdAt|date)|ago }}</small>
{% else %}
```
so it's already safe. (But I assume twigstan doesn't work well yet with is defined)

I feel like such error should be only report if this option is enabled
https://phpstan.org/config-reference#reportpossiblynonexistentgeneralarrayoffset

**Comment by ruudk** [comment]
Thanks for the report. You're correct. The `is defined` checks are not yet supported.

**Comment by ruudk** [comment]
`GetAttributeRule` should mimic PHPStan's `NonexistentOffsetInArrayDimFetchRule` and use `NonexistentOffsetInArrayDimFetchCheck`.
