### ISSUE TITLE
Reporting file and line number of real template

### ISSUE THREAD

**Issue by raffaelecarelle** [twigstan/twigstan#2]
Hello, 

Thank you for the great work of this tool!

A nice improve of it is reporting the real file and line number of twig file and not compiled one.

is it possibile?

Thank you so much!

**Comment by ruudk** [comment]
Thanks for your kind words.

It should work like that 🤔 

I just pushed a big refactoring. Please have a look and let me know how it works.

**Comment by ruudk** [comment]
See the screenshot in the new readme.

If the problem persists, please open a new issue with more details. 

Thanks for testing it out!
