### ISSUE TITLE
Analyze `{% include %}` and `{{ include() }}`

### ISSUE THREAD

**Issue by ruudk** [twigstan/twigstan#54]
Include [blocks](https://twig.symfony.com/doc/3.x/tags/include.html) and [functions](https://twig.symfony.com/doc/3.x/functions/include.html) are currently not analyzed.

Ideally, we see the include as a render point, and analyze the included template with the context from where it's rendered. 

Not sure how feasible that is.

**Comment by VincentLanglet** [comment]
If it's not easily doable, one great improvement would be to ignore all the template included.

One idea could be to only analyse template with context, with the following idea: 
- If I have an unused template, I don't want to report error on it since twigstan doesn't know how I will use it.

**Comment by VincentLanglet** [comment]
> But on the other hand: I was also thinking of creating a rule that would report errors when a template is not used (as render point, or extended from or included).

That require to have a perfect knowledge of all the render point.
This is for example not doable with dynamic render like
```
if ($twig->has($t)) {
     $twig->render($t);
} else {
     $twig->render('default');
}
```

Maybe later when the tool will be really aware of everything it could be a good rule, but as a start I think it's better to avoid as possible the false reports.
