### ISSUE TITLE
Baseline

### ISSUE THREAD

**Issue by ruudk** [twigstan/twigstan#9]
Just like PHPStan we need a baseline functionality.

**Comment by raffaelecarelle** [comment]
I have opened a pull request for this: https://github.com/twigstan/twigstan/pull/18

**Comment by ruudk** [comment]
TwigStan currently reports errors together with their "render point" (the place from where it's rendered). They contain line numbers. Example:
https://github.com/twigstan/twigstan/blob/d9f17f187b967e2a2d8e647094f46f2996bb8caf/tests/EndToEnd/RenderPoints/errors.json#L3-L13

This might be a problem for a baseline, as line numbers often change. We have to think about how to deal with that.

**Comment by ruudk** [comment]
As a first step, you can now manually ignore errors like this:
- https://github.com/twigstan/twigstan/pull/43

**Comment by raffaelecarelle** [comment]
@ruudk nice work, thank you!
